### ISSUE TITLE
Send update every second

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/delay-prediction-service#11]
In order to be able to display the UI immediately please send a message for each bus once every second even if it has not moved. Simply send the last know position and match.

**Comment by derhuerst** [comment]
The use case sounds a lot like it should be solved in the message transport layer, not in the business logic.

Can we use MQTT retained messages to fulfil it?

> If a broker receives a message on a topic for which there are no current subscribers, the broker discards the message unless the publisher of the message designated the message as a retained message. A retained message is a normal MQTT message with the retained flag set to true. The broker stores the last retained message and the corresponding QoS for the selected topic. Each client that subscribes to a topic pattern that matches the topic of the retained message receives the retained message immediately after they subscribe. The broker stores only one retained message per topic. This allows new subscribers to a topic to receive the most current value rather than waiting for the next update from a publisher.

https://en.wikipedia.org/wiki/MQTT#Overview

**Comment by derhuerst** [comment]
Unfortunately, mosquitto (the MQTT broker we use) seems to keep retained messages around forever.

> Retained Messages

All messages may be set to be retained. This means that the broker will keep the message even after sending it to all current subscribers. If a new subscription is made that matches the topic of the retained message, then the message will be sent to the client. This is useful as a "last known good" mechanism. If a topic is only updated infrequently, then without a retained message, a newly subscribed client may have to wait a long time to receive an update. With a retained message, the client will receive an instant update.

https://mosquitto.org/man/mqtt-7.html

It seems to only have a config to enable/disable retained messages, but not configure for how long it retains them.

https://mosquitto.org/man/mosquitto-conf-5.html

**Comment by leonardehrenfried** [comment]
What about https://github.com/eclipse/mosquitto/blob/master/mosquitto.conf#L104-L109 ?

**Comment by derhuerst** [comment]
> What about https://github.com/eclipse/mosquitto/blob/master/mosquitto.conf#L104-L109 ?

> ```
> # The maximum number of QoS 1 and 2 messages to hold in a queue per client
> # above those that are currently in-flight.  Defaults to 1000. Set
> # to 0 for no maximum (not recommended).
> # See also queue_qos0_messages.
> # See also max_queued_bytes.
> #max_queued_messages 1000
> ```

Even if we'd implement a mechanism to let a client re-connect with the same ID, that wouldn't help with new (as in never seen) clients, right?
