### ISSUE TITLE
Set the same GTFS-RT message content as Finland

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/delay-prediction-service#14]
Take a look at the contents of the GTFS-RT feed message here:

```
mqtt subscribe -l mqtt -p 1883 -h mqtt.waltti.fi -v -t "/gtfsrt/vp/Hameenlinna/#" -u user -P userpass
```

Fill the GTFS-RT message with the same content, if possible.

---

edited by @derhuerst:

An HSL GTFS-RT message looks like this:

```js
FeedEntity {
  id: '90880',
  is_deleted: false,
  vehicle: VehiclePosition {
    trip: TripDescriptor {
      trip_id: 'Kesä_21_ma-pe_9032_0_130000_134300_0',
      start_time: '13:00:00',
      start_date: '20210622',
      schedule_relationship: 0,
      route_id: '9032',
      direction_id: 0,
    },
    position: Position {
      latitude: 60.99900817871094,
      longitude: 24.47750473022461,
      bearing: 89.99999237060547,
      speed: 0.15396077930927277,
    },
    current_stop_sequence: 27,
    current_status: 2,
    timestamp: 1624357703,
    congestion_level: 0,
    stop_id: '154120',
    vehicle: VehicleDescriptor {
      id: '90880',
      label: '',
    },
  },
}
```

The following fields present in the HSL implementation are currently missing in `delay-prediction-service`:

- [x] `TripDescriptor.start_time` & `TripDescriptor.start_date`
- [x] ~~`TripDescriptor.direction_id`~~ irrelevant for Herrenberg for now
- [x] `VehiclePosition.current_stop_sequence`, `VehiclePosition.current_status` & `VehiclePosition.stop_id`
- [x] `Position.bearing` (nice-to-have)
- [ ] `Position.speed` (nice-to-have)

**Comment by derhuerst** [comment]
Closing as only the nice-to-have `Position.speed` is left.
