### ISSUE TITLE
add capacity information using pax counter data

### ISSUE THREAD

**Issue by derhuerst** [stadtnavi/delay-prediction-service#15]
Thingsboard has another metric `pax`, which contains the estimated nr of people in the bus. We should expose it as ~~[`CongestionLevel`](https://developers.google.com/transit/gtfs-realtime/reference/#enum-congestionlevel)~~ [`OccupancyStatus`](https://developers.google.com/transit/gtfs-realtime/reference/#enum-occupancystatus).

- [x] receive `pax` values
- [x] store `pax` values in `vehicle_positions`
- [x] convert latest `pax` value to `CongestionLevel`
- [x] write a test

existing implementation:

https://github.com/stadtnavi/thingsboard-to-gtfsrt-mqtt/blob/abfbca97df0bcaa1c14a89cbe9dbdebcde7b3816/thingsboard-to-gtfsrt-mqtt.py#L150-L157

**Comment by leonardehrenfried** [comment]
Wouldn't occupancy information be the better modelling: https://github.com/stadtnavi/thingsboard-to-gtfsrt-mqtt/blob/main/thingsboard-to-gtfsrt-mqtt.py#L176-L178
